acronyms = {
    "RTW": "Release That Witch",
    "ATG": "Against the Gods",
    "TDG": "Tales of Demons and Gods",
    "WMW": "Warlock of the Magus World",
    "ISSTH": "I Shall Seal the Heavens",
    "DE": "The Desolate Era",
    "ED": "Emperor's Domination",
    "MW": "Martial World",
    "AWE": "A Will Eternal",
    "SOTR": "Sovereign of the Three Realms",
    "LLS": "Long Live Summons!",
    "MGA": "Martial God Asura",
    "HJC": "Heavenly Jewel Change",
    "TMW": "True Martial World",
    "LOTM": "Lord of the Mysteries",
    "GDK": "Great Demon King",
    "LHP": "Library of Heaven's Path",
    "HSSB": "History's Strongest Senior Brother",
    "OEM": "Otherworldly Evil Monarch",
    "WOC": "World of Cultivation",
    "WDQK": "Wu Dong Qian Kun",
    "CCG": "Cultivation Chat Group",
    "DMWG": "Dragon - marked War God",
    "BTTH": "Battle Through the Heavens",
    "CSG": "Chaotic Sword God",
    "ST": "Stellar Transformation",
    "RI-WL": "Renegade Immortal",
    "RI-FY": "Reverend Insanity",
    "ZTJ": "Ze Tian Ji",
    "AST": "Ancient Strengthening Technique",
    "PMG": "Peerless Martial God",
    "RMJI": "A Record of a Mortal’s Journey to Immortality",
    "WDG": "World Defying Dan God",
    "TE": "Talisman Emperor",
    "DTPB": "Divine Throne of Primordial Blood",
    "FMC": "Forty Millenniums of Cultivation",
}
